; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; *** CUSTOM PARTITION TABLE (2MB SPIFFS) ***
board_build.partitions = partitions_no_ota.csv

; *** OPTIMIZATION FLAGS ***
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -Os
    -DCORE_DEBUG_LEVEL=0


; *** LIBRARIES ***
lib_deps = 
    mathieucarbou/AsyncTCP @ ^3.3.2
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0
    bblanchon/ArduinoJson @ ^7.4.2
    adafruit/Adafruit MPU6050 @ ^2.2.6
    kosme/arduinoFFT @ ^2.0.4
    knolleary/PubSubClient @ ^2.8
    
lib_ignore = 
    ESPAsyncTCP
    RPAsyncTCP
